spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotdeal

#      아래는 배포할 때만
#      username: taptorestart
#      password: thisispass
#      authentication-database: admin

server:
  port: 8080
  servlet:
    context-path: "/api"